print('DESAFIO 1')
nome = input ('qual é o seu nome? ')
print ('boas vindas',nome,('! Prazer te conhecer!'))

print('DESAFIO 2')
print ('digite sua data de nascimento')
dia = input ('dia = ')
mes = input ('mês = ')
ano = input ('ano = ')
#print ('você nasceu no dia',dia,'de',mes,'de',ano)
print ('vocÊ nasceu no dia {} de {} de {}'.format(dia,mes,ano))
print('DESAFIO 3')
X = int(input ('digite o primeiro número: '))
Y = int(input('digite o segundo número: '))
print ('O resultado é:',X + Y)
